import z from "zod"

export namespace McpCatalog {
  export const Entry = z.object({
    id: z.string(),
    name: z.string(),
    summary: z.string(),
    tier: z.number().int().positive(),
    tools: z.number().int().nonnegative(),
    techniques: z.number().int().positive().optional(),
    version: z.string(),
    package: z.string().optional(),
    repository: z.string().url(),
    command: z.array(z.string()).optional(),
    default: z.boolean(),
  })
  export type Entry = z.infer<typeof Entry>

  const entries = [
    {
      id: "github-security",
      name: "GitHub Security",
      summary: "Organization, repository, Actions, secrets, supply-chain, and access posture",
      tier: 1,
      tools: 39,
      version: "0.1.0",
      package: "github-security-mcp",
      repository: "https://github.com/badchars/github-security-mcp",
      command: ["npx", "-y", "github-security-mcp@0.1.0"],
      default: true,
    },
    {
      id: "cve",
      name: "CVE Intelligence",
      summary: "CVE enrichment, exploitability, exposure, affected packages, and ATT&CK",
      tier: 1,
      tools: 41,
      version: "0.2.0",
      package: "cve-mcp",
      repository: "https://github.com/badchars/cve-mcp",
      command: ["npx", "-y", "cve-mcp@0.2.0"],
      default: true,
    },
    {
      id: "osint",
      name: "OSINT",
      summary: "DNS, WHOIS, certificates, Shodan, Censys, VirusTotal, BGP, and archives",
      tier: 1,
      tools: 37,
      version: "0.2.0",
      package: "osint-mcp-server",
      repository: "https://github.com/badchars/osint-mcp-server",
      command: ["npx", "-y", "osint-mcp-server@0.2.0"],
      default: true,
    },
    {
      id: "cloud-audit",
      name: "Cloud Audit",
      summary: "AWS, Azure, and GCP security checks and attack-path correlation",
      tier: 1,
      tools: 38,
      version: "0.1.0",
      repository: "https://github.com/badchars/cloud-audit-mcp",
      default: true,
    },
    {
      id: "hackbrowser",
      name: "HackBrowser MCP",
      summary: "Firefox security browser with isolated roles, traffic replay, and active tests",
      tier: 1,
      tools: 39,
      version: "0.1.0",
      repository: "https://github.com/badchars/hackbrowser-mcp",
      default: true,
    },
    {
      id: "darknet",
      name: "Darknet Intelligence",
      summary: "Breach, ransomware, Tor, malware, blockchain, exploit, and stealer intelligence",
      tier: 2,
      tools: 66,
      version: "0.1.1",
      package: "darknet-mcp-server",
      repository: "https://github.com/badchars/darknet-mcp-server",
      command: ["npx", "-y", "darknet-mcp-server@0.1.1"],
      default: true,
    },
    {
      id: "dns-security",
      name: "DNS Security",
      summary: "DNSSEC, email security, hijacking, tunneling, typosquatting, and certificates",
      tier: 2,
      tools: 103,
      version: "0.1.0",
      package: "dns-security-mcp",
      repository: "https://github.com/badchars/dns-security-mcp",
      command: ["npx", "-y", "dns-security-mcp@0.1.0"],
      default: true,
    },
    {
      id: "supply-chain",
      name: "Supply Chain",
      summary: "Package risk, provenance, vulnerabilities, typosquatting, and dependency intelligence",
      tier: 2,
      tools: 7,
      techniques: 90,
      version: "0.2.1",
      package: "supply-chain-mcp-server",
      repository: "https://github.com/badchars/supply-chain-mcp-server",
      command: ["npx", "-y", "supply-chain-mcp-server@0.2.1"],
      default: true,
    },
    {
      id: "mcp-scanner",
      name: "MCP Security Scanner",
      summary: "Runtime, source, configuration, dependency, and OWASP MCP security analysis",
      tier: 3,
      tools: 55,
      version: "1.1.1",
      package: "mcp-security-scanner",
      repository: "https://github.com/badchars/mcp-security-scanner",
      command: ["npx", "-y", "mcp-security-scanner@1.1.1"],
      default: true,
    },
    {
      id: "steganography",
      name: "Steganography",
      summary: "Offline image, audio, video, document, archive, and covert-channel analysis",
      tier: 3,
      tools: 128,
      version: "0.2.0",
      package: "steganography-mcp",
      repository: "https://github.com/badchars/steganography-mcp",
      command: ["npx", "-y", "steganography-mcp@0.2.0"],
      default: true,
    },
    {
      id: "satellite",
      name: "Satellite and GEOINT",
      summary: "Imagery, aircraft, maritime, conflict, infrastructure, environmental, and cyber GEOINT",
      tier: 3,
      tools: 171,
      version: "0.1.0",
      package: "satellite-mcp",
      repository: "https://github.com/badchars/satellite-mcp",
      command: ["npx", "-y", "satellite-mcp@0.1.0"],
      default: true,
    },
    {
      id: "wifi-security",
      name: "Wireless Security",
      summary: "Wi-Fi, Bluetooth, RF/SDR, NFC/RFID, cellular, IoT, and WIDS/WIPS",
      tier: 4,
      tools: 34,
      version: "0.1.0",
      package: "wifi-security-mcp-server",
      repository: "https://github.com/badchars/wifi-security-mcp-server",
      command: ["npx", "-y", "wifi-security-mcp-server@0.1.0"],
      default: false,
    },
    {
      id: "lolbins",
      name: "Living off the Land",
      summary: "Cross-platform LOLBin intelligence, attack graphs, privilege, evasion, and detection",
      tier: 4,
      tools: 59,
      version: "0.1.0",
      package: "living-off-the-land-lolbins-mcp-server",
      repository: "https://github.com/badchars/living-off-the-land-lolbins-mcp-server",
      command: ["npx", "-y", "living-off-the-land-lolbins-mcp-server@0.1.0"],
      default: false,
    },
    {
      id: "fingerprint",
      name: "Fingerprinting",
      summary: "TCP, TLS, SSH, HTTP, DNS, WAF, IoT, mail, SMB, topology, and C2 fingerprints",
      tier: 4,
      tools: 100,
      version: "0.1.0",
      package: "fingerprint-mcp",
      repository: "https://github.com/badchars/fingerprint-mcp",
      command: ["npx", "-y", "fingerprint-mcp@0.1.0"],
      default: false,
    },
  ] satisfies Entry[]

  export function list() {
    return entries
  }

  export function defaults() {
    return Object.fromEntries(
      entries.flatMap((entry) => {
        if (!entry.default || !entry.command) return []
        return [[entry.id, { type: "local" as const, command: entry.command, enabled: false }] as const]
      }),
    )
  }
}
